"""
AI Agent Router System with Grok API (using requests - no base URL)
"""
"""
AI Agent Router System - Playwright Version
"""
import undetected_chromedriver as uc
import requests
from pydrive2.auth import GoogleAuth
from pydrive2.drive import GoogleDrive
import os
import time
import json
import subprocess
import webbrowser
import pyautogui
from dotenv import load_dotenv


# ── Force OAuth browser to Chrome (not Safari) ────────────────────────────────
class _ChromeBrowser(webbrowser.BaseBrowser):
    """Opens URLs in Google Chrome on macOS via the `open -a` command."""
    def open(self, url, new=0, autoraise=True):
        subprocess.Popen(['open', '-a', 'Google Chrome', url])
        return True

webbrowser.register('chrome', None, _ChromeBrowser(), preferred=True)
# ─────────────────────────────────────────────────────────────────────────────

# Load environment variables from .env file
load_dotenv()

# Configuration — key is loaded from .env, never hardcoded
GROK_API_KEY = os.getenv("GROQ_API_KEY")
if not GROK_API_KEY:
    raise EnvironmentError("❌ GROQ_API_KEY not found. Please set it in your .env file.")

# AI Agent Specializations
AI_AGENTS = {
    "claude": {
        "url": "https://claude.ai",
        "specialty": "coding, debugging, technical implementation, code review, algorithms",
        "textarea_selector": "div[contenteditable='true']",
        "response_selector": ".font-claude-message, .prose, [data-is-streaming='false']",
        "wait_time": 150,  # Claude takes longer to write code
        "submit_selector": "button[aria-label='Send Message']",
    },
    "perplexity": {
        "url": "https://www.perplexity.ai",
        "specialty": "research, fact-checking, current events, academic queries, citations",
        "textarea_selector": "div[contenteditable='true']#ask-input",
        "response_selector": ".prose, .break-words",
        "wait_time": 60,
        "submit_selector": "button[aria-label='Submit']",
    },
    "chatgpt": {
        "url": "https://chatgpt.com",
        "specialty": "general conversation, brainstorming, creative writing, everyday tasks",
        "textarea_selector": "#prompt-textarea",
        "response_selector": "[data-message-author-role='assistant']",
        "wait_time": 60,
        "submit_selector": "button[data-testid='send-button']",
    },
    "gemini": {
        "url": "https://gemini.google.com",
        "specialty": "multimodal tasks, Google integration, data analysis, summaries",
        "textarea_selector": "div[contenteditable='true'][role='textbox']",
        "response_selector": "model-response, .message-content",
        "wait_time": 60,
        "submit_selector": "button[aria-label='Send message']",
    }
}


def analyze_and_route_with_grok(notes):
    """Use your working Grok API implementation"""

    routing_prompt = f"""You are an intelligent AI routing system that creates CONTEXT-AWARE prompts across multiple AI agents.

    CORE PRINCIPLE - SEQUENTIAL PIPELINE:
    The AI agents will be executed in a STRICT SEQUENTIAL ORDER: Perplexity -> ChatGPT -> Claude -> Gemini.
    Because they run in this order, any agent executed later in the pipeline will AUTOMATICALLY receive the full outputs generated by the earlier agents as "Context".
    You DO NOT need to tell agents to "find" what the other agents wrote; they will be given it. Simply write their prompts assuming they have the context.

    ROUTING RULES & AGENT SELECTION:
    1. For coding/debugging/implementation/writing code → claude
    2. For research/facts/current events/latest data → perplexity  
    3. For general explanations/conceptual understanding/creative/learning advice → chatgpt
    4. For data analysis/synthesis/comparisons/summaries → gemini
    
    IMPORTANT ROUTING CONSTRAINTS (READ CAREFULLY):
    - DO NOT over-assign agents. If a prompt is simple or only needs 1-2 agents, ONLY assign 1-2 agents. Max 2 agents for most tasks unless highly complex.
    - If the user asks for pure CODE (e.g. "Write a script to do X"), DO NOT involve ChatGPT. Assign BOTH the explanation and the code generation to Claude.
    - If the user asks a theory question about coding WITHOUT needing actual code written (e.g., "What is the difference between TCP and UDP?"), DO NOT involve Claude. Assign it to Perplexity or ChatGPT.
    - Gemini is primarily for summarizing all the previous agents' work at the very end of the pipeline.

    Available AI Agents:
    - claude: {AI_AGENTS['claude']['specialty']}
    - perplexity: {AI_AGENTS['perplexity']['specialty']}
    - chatgpt: {AI_AGENTS['chatgpt']['specialty']}
    - gemini: {AI_AGENTS['gemini']['specialty']}

    User's notes/questions:
    {notes}

    TASK:
    1. Read the user's notes and figure out the core tasks.
    2. Decide which agents (min 1, max 4, usually 1-2) are required based on the constraints above.
    3. Write the specific prompts for those agents. Given that agents execute sequentially, later agents (like Claude or Gemini) can be given prompts like "Based on the context provided, write the code..." or "Summarize the findings from the previous agents...".

    Return ONLY valid JSON with this structure:
    {{
        "agent_name": {{
            "questions": ["question 1", "question 2", ...],
            "reasoning": "why this agent is selected based on the constraints"
        }}
    }}

    Only include agents that are explicitly needed. Return ONLY the JSON, no extra text."""

    try:
        # YOUR WORKING GROK API CALL HERE
        headers = {
            "Authorization": f"Bearer {GROK_API_KEY}",
            "Content-Type": "application/json"
        }

        payload = {
            "model": "llama-3.3-70b-versatile",
            "messages": [{"role": "user", "content": routing_prompt}],
            "temperature": 0.3
        }

        response = requests.post(
            "https://api.groq.com/openai/v1/chat/completions",
            headers=headers,
            json=payload
        )

        response_text = response.json()['choices'][0]['message']['content']
        json_start = response_text.find('{')
        json_end = response_text.rfind('}') + 1

        if json_start == -1:
            return {}

        routing_data = json.loads(response_text[json_start:json_end])
        return routing_data

    except Exception as e:
        print(f"❌ Grok API Error: {e}")
        return {}


def automate_ai_agents(routing_data):
    """Selenium + undetected-chromedriver version"""

    if not routing_data:
        print("❌ No agents to route to")
        return {}, {}

    from selenium.webdriver.common.by import By
    from selenium.webdriver.common.keys import Keys
    from selenium.webdriver.support.ui import WebDriverWait
    from selenium.webdriver.support import expected_conditions as EC

    # Setup undetected Chrome
    # Copy Chrome profile to a temp dir to avoid SingletonLock conflicts
    import shutil
    import tempfile
    chrome_profile_src = "/Users/hitarthtrivedi/Library/Application Support/Google/Chrome"
    temp_profile_dir = os.path.join(tempfile.gettempdir(), "uc_chrome_profile")

    # Clean up any previous temp profile
    if os.path.exists(temp_profile_dir):
        shutil.rmtree(temp_profile_dir, ignore_errors=True)

    # Copy only the Default profile (not the entire Chrome data dir)
    os.makedirs(temp_profile_dir, exist_ok=True)
    src_default = os.path.join(chrome_profile_src, "Default")
    dst_default = os.path.join(temp_profile_dir, "Default")
    if os.path.exists(src_default):
        shutil.copytree(src_default, dst_default, dirs_exist_ok=True,
                        ignore=shutil.ignore_patterns("SingletonLock", "SingletonCookie", "SingletonSocket", "*.lock"))

    # Also copy essential top-level files (Local State, etc.)
    for fname in ["Local State"]:
        src_file = os.path.join(chrome_profile_src, fname)
        if os.path.exists(src_file):
            shutil.copy2(src_file, os.path.join(temp_profile_dir, fname))

    options = uc.ChromeOptions()
    options.add_argument("--profile-directory=Default")
    options.add_argument("--disable-blink-features=AutomationControlled")

    # Use UC's built-in user_data_dir parameter (NOT as a Chrome argument)
    driver = uc.Chrome(
        options=options,
        user_data_dir=temp_profile_dir
    )

    EXECUTION_ORDER = ["perplexity", "chatgpt", "claude", "gemini"]
    
    print("\n" + "=" * 70)
    print("📋 STARTING SEQUENTIAL AGENT EXECUTION:")
    print("=" * 70)

    # Only run agents that were requested by Grok, in the defined order
    agents_to_run = [a for a in EXECUTION_ORDER if a in routing_data and a in AI_AGENTS]
    
    all_responses = {}
    agent_links = {}

    first_tab = True
    for agent_name in agents_to_run:
        data = routing_data[agent_name]
        agent_config = AI_AGENTS[agent_name]
        
        print(f"\n🚀 Opening {agent_name.upper()}...")
        print(f"   Reason: {data.get('reasoning', 'N/A')}")

        try:
            # Open new tab logic
            if not first_tab:
                driver.execute_script("window.open('');")
                time.sleep(1)
                driver.switch_to.window(driver.window_handles[-1])
            first_tab = False

            driver.get(agent_config["url"])
            time.sleep(4)

            # Build context string if there are past responses from other agents
            context_str = ""
            if all_responses:
                context_str = "Here is context from previous AI agents that you MUST use to inform your response. Do not hallucinate alternatives if the context provides the answer:\n\n"
                for prev_agent, prev_responses in all_responses.items():
                    context_str += f"--- Responses from {prev_agent.upper()} ---\n"
                    for r in prev_responses:
                        context_str += f"{r}\n\n"
                context_str += "Based on this context, please answer my following prompt(s):\n\n"

            # Send prompts
            for idx, prompt in enumerate(data["questions"], 1):
                try:
                    print(f"   → Question {idx}/{len(data['questions'])}: {prompt[:80]}...")

                    textarea = WebDriverWait(driver, 15).until(
                        EC.presence_of_element_located((By.CSS_SELECTOR, agent_config["textarea_selector"]))
                    )
                    textarea.clear()
                    
                    # Only inject context into the FIRST query for the agent
                    full_prompt = prompt
                    if idx == 1 and context_str:
                        full_prompt = context_str + prompt
                        
                    # Safely send multiline prompt without triggering premature submission (ENTER)
                    lines = full_prompt.split('\n')
                    for i, line in enumerate(lines):
                        if line:
                            textarea.send_keys(line)
                        if i < len(lines) - 1:
                            textarea.send_keys(Keys.SHIFT, Keys.ENTER)
                    time.sleep(1)
                    
                    submit_selector = agent_config.get("submit_selector")
                    submitted = False
                    if submit_selector:
                        try:
                            # Wait a moment for the submit button to become active
                            time.sleep(1)
                            submit_btn = WebDriverWait(driver, 5).until(
                                EC.element_to_be_clickable((By.CSS_SELECTOR, submit_selector))
                            )
                            submit_btn.click()
                            submitted = True
                            print("   🔘 Clicked submit button")
                        except Exception as e:
                            print(f"   ⚠️ Could not click submit button: {e}")
                    
                    if not submitted:
                        print("   ⌨️  Falling back to Keys.ENTER")
                        textarea.send_keys(Keys.ENTER)

                    time.sleep(45)  # Delay between prompts to allow text generation

                except Exception as e:
                    print(f"   ❌ Prompt error: {e}")

            # Wait for responses to finish generating
            wait_time = int(agent_config.get("wait_time", 60))
            print(f"   ⏳ Waiting {wait_time}s for final responses from {agent_name}...")
            time.sleep(wait_time)

            # Extract responses immediately
            selector = agent_config.get("response_selector", "[class*='message']")

            responses = []
            try:
                elements = driver.find_elements(By.CSS_SELECTOR, selector)
                if elements:
                    valid_elements = [el for el in elements if el.text.strip() and len(el.text.strip()) > 50]
                    # Grab the last N valid elements corresponding to the number of questions asked
                    for elem in valid_elements[-len(data["questions"]):]:
                        text = elem.text.strip()
                        responses.append(text)
            except Exception as e:
                print(f"   ❌ Extraction error: {e}")

            if responses:
                all_responses[agent_name] = responses
                agent_links[agent_name] = driver.current_url
                print(f"   ✅ Collected {len(responses)} responses from {agent_name}")
                print(f"   🔗 Chat Link: {driver.current_url}")
                
                print(f"\n{'─' * 70}")
                for idx, resp in enumerate(responses, 1):
                    print(f"   [Response {idx} Snippet]: {resp[:200]}...")
                print(f"{'─' * 70}\n")
            else:
                print(f"   ⚠️ No responses captured from {agent_name}")

        except Exception as e:
            print(f"   ❌ Failed to process {agent_name}: {e}")

    print(f"\n{'=' * 70}\n")


    return all_responses, agent_links


def main():
    prev=open('prev_notes.txt','r')
    prev_content=prev.read()
    print(prev_content)
    # Google Drive Authentication with settings
    gauth = GoogleAuth(settings_file='settings.yaml')

    # Try to load saved credentials
    gauth.LoadCredentialsFile("credentials.json")

    def _login_with_chrome():
        """Run LocalWebserverAuth with Chrome forced as the browser."""
        # Temporarily set Chrome as the only option so webbrowser.open() picks it
        webbrowser._tryorder = ['chrome']  # noqa: SLF001
        gauth.LocalWebserverAuth()

    if gauth.credentials is None:
        # No credentials saved — do full OAuth login
        print("🔐 No credentials found. Opening Google login in Chrome...")
        _login_with_chrome()
    elif gauth.access_token_expired:
        # Try to refresh; if token is revoked, do a fresh login
        try:
            gauth.Refresh()
        except Exception as refresh_error:
            error_str = str(refresh_error).lower()
            if "invalid_grant" in error_str or "revoked" in error_str or "expired" in error_str:
                print(f"⚠️  Token refresh failed (invalid/revoked): {refresh_error}")
                print("🔄 Token revoked/expired — deleting old credentials and re-authenticating in Chrome...")
                creds_path = "credentials.json"
                if os.path.exists(creds_path):
                    os.remove(creds_path)
                _login_with_chrome()
            else:
                print(f"⚠️  Token refresh failed (likely network error): {refresh_error}")
                print("🔄 Will not delete credentials. Exiting to retry later...")
                return
    else:
        # Valid credentials — just authorise
        gauth.Authorize()

    # Save credentials for next time
    gauth.SaveCredentialsFile("credentials.json")

    drive = GoogleDrive(gauth)

    # Read notes.txt from Drive
    file_list = drive.ListFile({'q': "title='notes.txt'"}).GetList()

    if not file_list:
        print("❌ notes.txt not found in Google Drive!")
        return

    file = file_list[0]
    user_notes = file.GetContentString()
    if user_notes!=prev_content:
        print("\n" + "=" * 70)
        print("🤖 AI AGENT ROUTER SYSTEM (Playwright)")
        print("=" * 70)
        print("\n📝 Your Notes:")
        print(user_notes)
        with open('prev_notes.txt','w') as u_notes:
            u_notes.write(user_notes)



        print("\n🧠 Grok analyzing and routing...\n")
        routing_data = analyze_and_route_with_grok(user_notes)

        if routing_data:
            print("📊 ROUTING DECISIONS:")
            print(json.dumps(routing_data, indent=2))

            responses, links = automate_ai_agents(routing_data)

            if responses:
                with open("ai_responses.json", "w", encoding="utf-8") as f:
                    json.dump(responses, f, indent=2, ensure_ascii=False)
                print("\n💾 Responses saved to ai_responses.json")
                
            if links:
                with open("ai_links.txt", "w", encoding="utf-8") as f:
                    f.write("🔗 AI Agent Chat Links 🔗\n")
                    f.write("=" * 50 + "\n\n")
                    for agent, url in links.items():
                        f.write(f"{agent.upper()}:\n{url}\n\n")
                print("💾 Links saved to ai_links.txt")
                file2 = drive.CreateFile({'title': 'ai_links.txt'}) # Set the desired title on Drive
                file2.SetContentFile('ai_links.txt') # Read file and set it as the content
                file2.Upload()
        else:
            print("\n❌ No routing data from Grok")

    else:
        print("its the same")

# Rest of your existing code...





if __name__ == "__main__":
    main()
